#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
feh --bg-fill ~/Pictures/bg.jpg &
picom &
nm-applet &
setxkbmap -option grp:alt_shift_toggle us,ir &



if [[ $(xrandr -q | grep 'HDMI-1 connected') ]];
then
	bspc monitor eDP-1 -d 1 2 3 4	
	bspc monitor HDMI-1 -d 5 6 7 8
else
	bspc monitor eDP-1 -d 1 2 3 4
fi

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer	true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
